//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurtlePay_Identity_Todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.Groups1 = new HashSet<Group>();
        }
    
        public int GroupID { get; set; }
        public Nullable<int> OrganisationID { get; set; }
        public Nullable<int> ParentGroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> GroupType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups1 { get; set; }
        public virtual Group Group1 { get; set; }
        public virtual GroupType GroupType1 { get; set; }
        public virtual Organisation Organisation { get; set; }
    }
}
