//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurtlePay_Identity_Todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public int OrgId { get; set; }
        public string OrgName { get; set; }
        public string OrgType { get; set; }
        public string OrgCategory { get; set; }
    }
}
