// <auto-generated />
namespace TurtlePay_Identity_Todo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GroupAndOrgIds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GroupAndOrgIds));
        
        string IMigrationMetadata.Id
        {
            get { return "201604122348128_GroupAndOrgIds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
