// <auto-generated />
namespace TurtlePay_Identity_Todo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserMobile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserMobile));
        
        string IMigrationMetadata.Id
        {
            get { return "201604010441191_UserMobile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
